image: microsoft/aspnetcore-build:1.0-1.1

before_script:
  - cd
  
stages:
  - build
  
build_job:
  stage: build
  script:
    - dotnet restore ./WetPicsTelegramBot.sln 
    - dotnet publish ./WetPicsTelegramBot.sln -c Release -o ./obj/Docker/publish
    - dir /s
  artifacts:
    paths:
      untracked: true