image: microsoft/aspnetcore-build:1.0-1.1

before_script:
  - ls -a1
  
stages:
  - build
  
build_job:
  stage: build
  script:
    - dotnet restore ./WetPicsTelegramBot.sln 
    - dotnet publish ./WetPicsTelegramBot.sln -c Release -o ./obj/Docker/publish
    - ls -a1
  artifacts:
    untracked: true