FROM microsoft/dotnet:2.0-sdk
WORKDIR /app

COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o out

ENV ASPNETCORE_ENVIRONMENT Development

ENTRYPOINT ["dotnet", "out/WetPicsTelegramBot.dll"]
