version: '2'

services:
  wetpicstelegrambot:
    image: wetpicstelegrambot:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ./WetPicsTelegramBot:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
