version: '3'

services:
  ci-build:
    image: microsoft/dotnet:latest
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./WetPicsTelegramBot/WetPicsTelegramBot.csproj && dotnet publish ./WetPicsTelegramBot/WetPicsTelegramBot.csproj -c Release -o ./obj/Docker/publish"
