version: '3'

services:
  postgresserver:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  wetpicstelegrambot:
    image: wetpicstelegrambot
    restart: always
    depends_on: 
      - postgresserver
    links:
      - postgresserver
    networks:
      - mynetwork
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config

networks:
  mynetwork:
     driver: bridge

volumes:
   pgdata: