version: '3'

services:
  postgresserver:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
      
  wetpicstelegrambot.webapp:
    image: wetpicstelegrambot.webapp
    build:
        context: ./WetPicsTelegramBot.WebApp
        dockerfile: Dockerfile
    depends_on: 
      - postgresserver
    links:
      - postgresserver
    networks:
      - mynetwork
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  mynetwork:
     driver: bridge

volumes:
   pgdata:
